# Generated by Django 3.2.7 on 2021-09-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('acronym', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('ticker', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Биржа',
                'verbose_name_plural': 'Биржи',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Рынок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Рынок',
                'verbose_name_plural': 'Рынки',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Timeframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Symbol', to='analytics.asset')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.exchange')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.market')),
                ('second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='analytics.asset')),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации на TV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('chart_one', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('chart_two', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('chart_three', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('chart_four', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('chart_five', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано?')),
                ('views', models.IntegerField(default=0)),
                ('locale', models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Русский')], default='en', max_length=2, null=True)),
                ('label', models.CharField(blank=True, choices=[('long', 'Покупать'), ('short', 'Продавать'), ('education', 'Обучение'), ('neutral', 'Нейтрально')], max_length=10, null=True)),
                ('publication_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tp_price_first', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tp_price_second', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tp_price_third', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sl_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lowest_price_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('highest_price_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('channel', models.ManyToManyField(blank=True, related_name='posts', to='analytics.Channel')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.symbol', verbose_name='Тикер TV')),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.timeframe', verbose_name='Таймфрэйм')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Аналитика',
                'ordering': ['-published_at'],
            },
        ),
    ]
