# Generated by Django 3.2.7 on 2021-09-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ['title'], 'verbose_name': 'Тикер', 'verbose_name_plural': 'Тикеры'},
        ),
        migrations.AddField(
            model_name='analysis',
            name='link_to_TV',
            field=models.URLField(blank=True, null=True),
        ),
    ]
