# Generated by Django 3.2.7 on 2021-09-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20210919_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='chart_one',
        ),
        migrations.AddField(
            model_name='analysis',
            name='content_upd_one',
            field=models.TextField(blank=True, verbose_name='Обновление 1'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='photo_upd_one',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='График 1'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='chart_five',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='График 5'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='chart_four',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='График 4'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='chart_three',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='График 3'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='chart_two',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='График 2'),
        ),
    ]
