# Generated by Django 3.2.7 on 2021-09-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20210920_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='chart_five',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='chart_four',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='chart_three',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='chart_two',
        ),
        migrations.AddField(
            model_name='analysis',
            name='content_upd_five',
            field=models.TextField(blank=True, verbose_name='Обновление 1'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='content_upd_four',
            field=models.TextField(blank=True, verbose_name='Обновление 1'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='content_upd_three',
            field=models.TextField(blank=True, verbose_name='Обновление 1'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='content_upd_two',
            field=models.TextField(blank=True, verbose_name='Обновление 1'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='photo_upd_five',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото обновления 5'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='photo_upd_four',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото обновления 4'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='photo_upd_three',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото обновления 3'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='photo_upd_two',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото обновления 2'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='published_upd_five',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации на TV'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='published_upd_four',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации на TV'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='published_upd_one',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации на TV'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='published_upd_three',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации на TV'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='published_upd_two',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации на TV'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='related_analysis_five',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='related_analysis_four',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='related_analysis_one',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='related_analysis_three',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='related_analysis_two',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='photo_upd_one',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото обновления 1'),
        ),
    ]
