# Generated by Django 3.2.7 on 2021-09-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_analysis_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='slide_title',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Слайд'),
        ),
    ]
