# Generated by Django 3.2.7 on 2021-09-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_analysis_slide_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='slide_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование слайда'),
        ),
    ]
