# Generated by Django 3.2.7 on 2021-09-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_auto_20210926_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
