# Generated by Django 3.2.7 on 2021-09-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='title',
        ),
    ]
