# Generated by Django 3.2.7 on 2021-09-27 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_remove_rating_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата добавления')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('entry', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sl', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('result', models.CharField(choices=[('w', 'Win'), ('l', 'Loss'), ('c', 'Canceled')], max_length=1)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='analytics.status')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.symbol', verbose_name='Тикер TV')),
            ],
        ),
    ]
